instagram_data = [
    {"name": "Instagram", "followers_count": 698_000_000, "description": "Official Instagram account", "country": "United States"},
    {"name": "Cristiano Ronaldo", "followers_count": 670_000_000, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "followers_count": 510_000_000, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "followers_count": 416_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kylie Jenner", "followers_count": 391_000_000, "description": "Entrepreneur and media personality", "country": "United States"},
    {"name": "Dwayne Johnson", "followers_count": 391_000_000, "description": "Actor and former wrestler", "country": "United States"},
    {"name": "Ariana Grande", "followers_count": 372_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kim Kardashian", "followers_count": 354_000_000, "description": "Media personality", "country": "United States"},
    {"name": "Beyoncé", "followers_count": 308_000_000, "description": "Singer and businesswoman", "country": "United States"},
    {"name": "Khloe Kardashian", "followers_count": 300_000_000, "description": "TV personality", "country": "United States"},

    {"name": "Nike", "followers_count": 298_000_000, "description": "Sportswear brand", "country": "United States"},
    {"name": "Justin Bieber", "followers_count": 292_000_000, "description": "Singer", "country": "Canada"},
    {"name": "Kendall Jenner", "followers_count": 285_000_000, "description": "Model", "country": "United States"},
    {"name": "Taylor Swift", "followers_count": 281_000_000, "description": "Singer-songwriter", "country": "United States"},
    {"name": "National Geographic", "followers_count": 276_000_000, "description": "Media and photography", "country": "United States"},
    {"name": "Virat Kohli", "followers_count": 274_000_000, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "followers_count": 247_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Neymar Jr", "followers_count": 231_000_000, "description": "Footballer", "country": "Brazil"},
    {"name": "Kourtney Kardashian", "followers_count": 216_000_000, "description": "TV personality", "country": "United States"},
    {"name": "Miley Cyrus", "followers_count": 211_000_000, "description": "Singer and actress", "country": "United States"},

    {"name": "Katy Perry", "followers_count": 202_000_000, "description": "Singer", "country": "United States"},
    {"name": "Zendaya", "followers_count": 176_000_000, "description": "Actress and singer", "country": "United States"},
    {"name": "Kevin Hart", "followers_count": 176_000_000, "description": "Comedian and actor", "country": "United States"},
    {"name": "Cardi B", "followers_count": 163_000_000, "description": "Rapper", "country": "United States"},
    {"name": "LeBron James", "followers_count": 158_000_000, "description": "Basketball player", "country": "United States"},
    {"name": "Demi Lovato", "followers_count": 152_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Rihanna", "followers_count": 149_000_000, "description": "Singer and entrepreneur", "country": "Barbados"},
    {"name": "Chris Brown", "followers_count": 144_000_000, "description": "Singer", "country": "United States"},
    {"name": "Drake", "followers_count": 142_000_000, "description": "Rapper", "country": "Canada"},

    {"name": "Ellen DeGeneres", "followers_count": 134_000_000, "description": "TV host", "country": "United States"},
    {"name": "Kylian Mbappe", "followers_count": 128_000_000, "description": "Footballer", "country": "France"},
    {"name": "Billie Eilish", "followers_count": 124_000_000, "description": "Singer", "country": "United States"},
    {"name": "Gal Gadot", "followers_count": 106_000_000, "description": "Actress", "country": "Israel"},
    {"name": "Vin Diesel", "followers_count": 104_000_000, "description": "Actor", "country": "United States"},
    {"name": "Narendra Modi", "followers_count": 99_000_000, "description": "Prime Minister of India", "country": "India"},
    {"name": "NASA", "followers_count": 97_000_000, "description": "Space agency", "country": "United States"},
    {"name": "Shakira", "followers_count": 95_000_000, "description": "Singer", "country": "Colombia"},
    {"name": "Priyanka Chopra", "followers_count": 93_000_000, "description": "Actress", "country": "India"},

    {"name": "NBA", "followers_count": 90_000_000, "description": "Basketball league", "country": "United States"},
    {"name": "Dua Lipa", "followers_count": 88_000_000, "description": "Singer", "country": "United Kingdom"},
    {"name": "Snoop Dogg", "followers_count": 88_000_000, "description": "Rapper", "country": "United States"},
    {"name": "David Beckham", "followers_count": 88_000_000, "description": "Former footballer", "country": "United Kingdom"},
    {"name": "Alia Bhatt", "followers_count": 86_000_000, "description": "Actress", "country": "India"},
    {"name": "Robert Downey Jr.", "followers_count": 83_000_000, "description": "Actor", "country": "United States"},
    {"name": "Chris Hemsworth", "followers_count": 82_000_000, "description": "Actor", "country": "Australia"},
    {"name": "Emma Watson", "followers_count": 74_000_000, "description": "Actress", "country": "United Kingdom"},
    {"name": "Shawn Mendes", "followers_count": 72_000_000, "description": "Singer", "country": "Canada"},

    {"name": "Will Smith", "followers_count": 69_000_000, "description": "Actor", "country": "United States"},
    {"name": "Gigi Hadid", "followers_count": 77_000_000, "description": "Model", "country": "United States"},
    {"name": "Zlatan Ibrahimovic", "followers_count": 63_000_000, "description": "Footballer", "country": "Sweden"},
    {"name": "Lewis Hamilton", "followers_count": 38_000_000, "description": "Formula 1 driver", "country": "United Kingdom"},
    {"name": "Conor McGregor", "followers_count": 46_000_000, "description": "MMA fighter", "country": "Ireland"},
    {"name": "Khabib Nurmagomedov", "followers_count": 36_000_000, "description": "Former MMA champion", "country": "Russia"},
    {"name": "Bad Bunny", "followers_count": 45_000_000, "description": "Latin music artist", "country": "Puerto Rico"},
    {"name": "Maluma", "followers_count": 63_000_000, "description": "Singer", "country": "Colombia"},
    {"name": "J Balvin", "followers_count": 52_000_000, "description": "Reggaeton artist", "country": "Colombia"}
]


